services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"

  app:
    build: .
    platform: linux/amd64
    ports:
      - "8010:8010"
    depends_on:
      - qdrant
